### PR TITLE
never gonna do this again, optimizing

### PR DESCRIPTION
**Pull request by cloudcloudskies**
optimized the whole thing, never doing these again bc of the asm scripts, theyre so hard to optimize.

changelog:
main.py: Instead of computing the gradient length in each call to _asciify_image, it's precomputed during initialization of CustomConverter this avoids repetitive calculations
rather than accumulating all data in memory and writing it to the file at once, each frame is directly written to the file this reduces memory usage, especially for large videos
Slicing the last character of the encoded text (removing the newline character) is done directly during encoding, avoiding unnecessary string manipulation
the vars (parser.parse_args()) was replaced with direct usage of args to improve readability and avoid unnecessary function calls

bootloader:
eliminate instructions that are redundant or not essential for the bootloader's functionality
simplify the loop structure to reduce the number of instructions executed per iteration
minimize memory accesses and use more efficient memory access techniques where possible
simplified interrupt handling to reduce overhead

disk:
Utilize registers effectively to minimize memory access and improve performance
Minimize the number of conditional jump instructions by restructuring the logic
Remove redundant comments that simply repeat what the code does without adding value
Combine common operations to reduce instruction count
Avoid function calls for simple operations to eliminate overhead

pit:
Removed unnecessary comments for clarity (YEA)
Used the actual value of PIT_RELOAD_VALUE instead
Utilized cs segment register directly for setting up IVT segment
Removed unnecessary register manipulation

print:
Reordered the carriage return and line feed characters in the line_break subroutine to ensure correct newline behavior
Used test al, al instead of cmp al, 0x00 to check for a null character in the print subroutine, which sets the zero flag without modifying any registers, providing a more efficient way to check for null
Replaced separate instructions for clearing dl and dh with xor instructions, which are shorter and faster (idk how much fast tho but rlly fast ig??)

hex printer:
This optimization eliminates redundancy by combining the conversion and printing of the high and low nibbles into one function (print_hex_digit) also, unnecessary conditional jumps are removed by checking if the value is less than or equal to '9' before adjusting it to the correct ASCII character, thus improving code efficiency (nice)

### CODE REVIEW

**Comment by bemxio** [comment]
i checked it up and refactored some stuff, feel free to add any more changes if there are any to be done and tell me when it's ready to merge

> optimized the whole thing, never doing these again bc of the asm scripts, theyre so hard to optimize.

i get you, it's really hard to write assembly better than what a compiler would produce, but in this case you can't really use C since it's too big (and you would need to write your own stdlib either in assembly or using `__asm__`)
i am still impressed that you still could shorten some stuff, although please try to test each commit if it compiles and runs successfully, i had to do some changes in order for it to proceed with building it

> Slicing the last character of the encoded text (removing the newline character) is done directly during encoding, avoiding unnecessary string manipulation

the last character is actually not a newline, its just a dirty hack for the teletype mode to not move onto the next line, thereby hiding the first row of the frame
i thought about rewriting the print so that it manually moves the cursor and places the character at the right place so that the last character (right bottom corner) will be shown, but i think that would reduce performance by a lot

> Removed unnecessary comments for clarity (YEA)

haha, this project was my first large one when it comes to assembly, and so i got a habit of commenting each line, to not get lost at the beginning

> Used the actual value of PIT_RELOAD_VALUE instead

`PIT_RELOAD_VALUE` as well as `FRAME_COUNT` is provided at compilation time from the `Makefile`, not so long ago i've expanded the `Makefile` to calculate those values inside of it based on the video file

**Comment by cloudcloudskies** [comment]
there is nothing to do ig, also i can compile at least, but i cant test it sadly

**Comment by bemxio** [comment]
it's all good, rebased the commits to the main branch, thank you once again for the hard work with assembly!

**Comment by cloudcloudskies** [comment]
tysm!! :D also do you have a discord? my discord is cloudcloudskies

**Pull request merged**
